GPT-2 Plugin
basement-drift/shrek pull request #5
Opened 2020-01-17 00:51 UTC by frazerk

2020-01-17 20:59 UTC, evpotter requested changes

2020-01-17 20:59 UTC, evpotter commented on plugins/gpt2.py
> +import os
this file has too much python

2020-01-17 21:00 UTC, frazerk commented on plugins/gpt2.py
> +import os
oh dang

2020-01-19 14:35 UTC, evpotter commented
I also feel there should be a description about what the PR does. At least more than "GPT-2 Plugin". Also commit messages should follow more closely with this: [Git Commits](https://chris.beams.io/posts/git-commit/)

2020-01-19 15:03 UTC, frazerk commented
I can be more descriptive in the future, but I figured it was unnecessary since a) this is a silly chatbot and b) you guys had already seen this code in action.

2020-01-19 15:06 UTC, evpotter commented
I'm just being an asshole lol I guess my joke didn't hit :(

2020-01-19 15:07 UTC, frazerk commented
Please remove the Santa Hat from the VS Code logo

2020-01-19 15:07 UTC, evpotter approved these changes

2020-01-19 15:08 UTC, merged